name: app_abelhas
description: "BeeSafe App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  flutter_dotenv: ^5.2.1
  get_it: ^8.2.0
  dio: ^5.8.0+1
  google_maps_flutter: ^2.12.3
  provider: ^6.1.5
  feather_icons: ^1.2.0
  package_info_plus: ^8.3.0
  geolocator: ^12.0.0
  supabase_flutter: ^2.9.1
  dartz: ^0.10.1
  flutter_multi_formatter: ^2.13.8
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  intl: ^0.20.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  shared_preferences: ^2.5.4
  firebase_messaging: ^16.1.0
  firebase_core: ^4.3.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
